//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustShop.Dao_JustShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPhieunhap
    {
        public int MaPhieuNhap { get; set; }
        public int MaCTPhieuNhap { get; set; }
        public int MaSp { get; set; }
        public Nullable<int> Soluong { get; set; }
        public Nullable<double> GiaNhap { get; set; }
        public int MaLoai { get; set; }
    
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        public virtual PhieuNhapHang PhieuNhapHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
