//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustShop.Dao_JustShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanHoi
    {
        public int STT { get; set; }
        public string Ten { get; set; }
        public string Email { get; set; }
        public int DienThoai { get; set; }
        public string TieuDePhanHoi { get; set; }
        public string NoiDungPhanHoi { get; set; }
    }
}
