//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO_JustShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTDonHang
    {
        public int MaCT { get; set; }
        public int MaDonHang { get; set; }
        public int MaSp { get; set; }
        public int SoLuong { get; set; }
        public double Gia { get; set; }
        public double GiaTien { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
