//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO_JustShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongKe
    {
        public int ID { get; set; }
        public Nullable<int> SoLuongBan { get; set; }
        public Nullable<double> TongDoanhThu { get; set; }
        public Nullable<int> SoLuongDonHang { get; set; }
        public string SanPhamBanChay { get; set; }
        public int Ngay { get; set; }
    }
}
